### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by rasif-sahl** [rasif-sahl/php#1]
- [x] Connecting with cloud-flare
- [x] Creating a sub-branch for the development.
- [x] Creating the navigation / top bar
- [x] creating the side navigation section.
- [x] Creating the footer section.
- [x] creating the content display section.
- [x] creating the right single-page navigation section.
- [x] Writing the content accordingly.
